moodle:
  #image: moodle
  build: .
  volumes:
   - moodledata:/var/moodledata
  ports:
   - "80:80"
  environment:
   - MOODLE_URL=http://127.0.0.1
   - MOODLE_DB_HOST=10.1.2.47
   - MOODLE_DB_NAME=moodle
   - MOODLE_DB_USER=saberes
   - MOODLE_DB_PASS=senhas@beres
